# Generated by Django 5.2.18 on 2026-10-07 10:44

import accounts.models
import core.storage
import core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[core.validators.validate_phone], verbose_name='telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, verbose_name='ism')),
                ('last_name', models.CharField(max_length=150, verbose_name='familiya')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('teacher', 'Ustoz'), ('student', 'Student')], db_index=True, default='student', max_length=20, verbose_name='rol')),
                ('avatar', models.ImageField(blank=True, upload_to=core.storage.UUIDUploadPath('avatars'), verbose_name='rasm')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django admin')),
                ('must_change_password', models.BooleanField(default=False)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'ordering': ['last_name', 'first_name', 'id'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150)),
                ('parent_phone', models.CharField(blank=True, max_length=16, validators=[core.validators.validate_phone])),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='ichki izoh')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profillar',
            },
        ),
    ]
