# Generated by Django 5.2.18 on 2026-10-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_grades', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grade', to='assignments.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'baho',
                'verbose_name_plural': 'baholar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GradeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('previous_comment', models.TextField(blank=True)),
                ('new_comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='grades.grade')),
            ],
            options={
                'verbose_name': "baho o'zgarishi",
                'verbose_name_plural': "baho o'zgarishlari",
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'group'], name='grades_student_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', models.F('max_score'))), name='grades_score_within_bounds', violation_error_message="Ball 0 dan maksimal ballgacha bo'lishi kerak."),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='grades_max_score_positive'),
        ),
    ]
