# Generated by Django 5.2.18 on 2026-10-07 10:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='kodi')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('status', models.CharField(choices=[('forming', 'Shakllanmoqda'), ('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='forming', max_length=20)),
                ('start_date', models.DateField(verbose_name='boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='tugash sanasi')),
                ('capacity', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name="sig'im")),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('lesson_start_time', models.TimeField(blank=True, null=True)),
                ('lesson_end_time', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='organizations.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='courses.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='organizations.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guruh',
                'verbose_name_plural': 'guruhlar',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('frozen', 'Muzlatilgan'), ('completed', 'Bitirgan'), ('left', 'Chiqib ketgan'), ('transferred', "Ko'chirilgan")], db_index=True, default='active', max_length=20)),
                ('joined_at', models.DateField(verbose_name="qo'shilgan sana")),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='chiqqan sana')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="oylik to'lov")),
                ('discount_type', models.CharField(choices=[('none', 'Chegirmasiz'), ('percent', 'Foiz'), ('fixed', 'Belgilangan summa')], default='none', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='groups.groupmembership')),
            ],
            options={
                'verbose_name': "guruh a'zoligi",
                'verbose_name_plural': "guruh a'zoliklari",
                'ordering': ['-joined_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch', 'status'], name='groups_group_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='groups_group_dates_ordered', violation_error_message="Tugash sanasi boshlanish sanasidan oldin bo'lishi mumkin emas."),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('lesson_start_time__isnull', True), ('lesson_end_time__isnull', True), ('lesson_end_time__gt', models.F('lesson_start_time')), _connector='OR'), name='groups_group_times_ordered', violation_error_message="Dars tugash vaqti boshlanish vaqtidan keyin bo'lishi kerak."),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student', 'status'], name='groups_membership_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'frozen'])), fields=('group', 'student'), name='groups_membership_one_open_per_group', violation_error_message="Student bu guruhda allaqachon faol a'zo."),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='groups_membership_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_fee__gte', 0)), name='groups_membership_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0), models.Q(models.Q(('discount_type', 'percent'), _negated=True), ('discount_value__lte', 100), _connector='OR'), models.Q(models.Q(('discount_type', 'fixed'), _negated=True), ('discount_value__lte', models.F('monthly_fee')), _connector='OR')), name='groups_membership_discount_valid'),
        ),
    ]
