# Generated by Django 5.2.18 on 2026-10-07 10:44

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nomi')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{2,20}$', "Kod 2-20 ta katta lotin harfi, raqam yoki '-' bo'lsin.")], verbose_name='kodi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[core.validators.validate_phone], verbose_name='telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="sig'imi")),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='organizations.branch')),
            ],
            options={
                'verbose_name': 'xona',
                'verbose_name_plural': 'xonalar',
                'ordering': ['branch_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'name'), name='organizations_room_unique_name_per_branch', violation_error_message='Bu filialda shu nomli xona mavjud.')],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(default='EduCentr', max_length=150)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('attendance_excused_policy', models.CharField(choices=[('exclude', 'Hisobdan chiqariladi'), ('present', 'Keldi deb hisoblanadi'), ('absent', 'Kelmadi deb hisoblanadi')], default='exclude', max_length=10)),
                ('attendance_late_counts_present', models.BooleanField(default=True)),
                ('attendance_edit_window_hours', models.PositiveSmallIntegerField(default=48, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)])),
                ('max_upload_mb', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('allowed_upload_extensions', models.CharField(default='pdf,doc,docx,txt,zip,rar,7z,png,jpg,jpeg,py,js,ts,html,css,json,ipynb,pptx,xlsx', max_length=500)),
                ('invoice_due_day', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('payment_void_window_hours', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(720)])),
                ('teacher_reward_limit', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tizim sozlamalari',
                'verbose_name_plural': 'tizim sozlamalari',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='organizations_settings_singleton')],
            },
        ),
    ]
