# Generated by Django 5.2.18 on 2026-10-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='sana')),
                ('start_time', models.TimeField(verbose_name='boshlanish')),
                ('end_time', models.TimeField(verbose_name='tugash')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='mavzu')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('completed', "O'tilgan"), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='groups.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='organizations.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dars',
                'verbose_name_plural': 'darslar',
                'ordering': ['date', 'start_time', 'id'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='schedules_lesson_when_idx'), models.Index(fields=['teacher', 'date'], name='schedules_lesson_teacher_idx'), models.Index(fields=['room', 'date'], name='schedules_lesson_room_idx'), models.Index(fields=['group', 'date'], name='schedules_lesson_group_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedules_lesson_times_ordered', violation_error_message="Dars tugash vaqti boshlanish vaqtidan keyin bo'lishi kerak."), models.UniqueConstraint(fields=('group', 'date', 'start_time'), name='schedules_lesson_unique_slot_per_group', violation_error_message='Bu guruhda shu vaqtda dars mavjud.')],
            },
        ),
    ]
