# Generated by Django 5.2.18 on 2026-10-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('attendance', 'Davomat'), ('homework', 'Uy vazifasi'), ('activity', 'Faollik'), ('behavior', 'Xulq'), ('manual', "Qo'lda"), ('redeem', 'Sarflandi'), ('penalty', 'Jarima')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_rewards', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coin tranzaksiyasi',
                'verbose_name_plural': 'coin tranzaksiyalari',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='rewards_student_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='rewards_amount_non_zero')],
            },
        ),
    ]
