# Generated by Django 5.2.18 on 2026-10-07 10:44

import core.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='kodi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('duration_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='davomiyligi (oy)')),
                ('lessons_per_week', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('lesson_duration_minutes', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='oylik narx')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organizations.branch')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'kurslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, storage=core.storage.PrivateMediaStorage(), upload_to=core.storage.UUIDUploadPath('materials'))),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kurs materiali',
                'verbose_name_plural': 'kurs materiallari',
                'ordering': ['course_id', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0)), name='courses_course_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coursematerial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file', ''), _negated=True), models.Q(('url', ''), _negated=True), _connector='OR'), name='courses_material_file_or_url'),
        ),
    ]
