# Generated by Django 5.2.18 on 2026-10-07 10:44

import core.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('grading_criteria', models.TextField(blank=True, verbose_name='baholash mezoni')),
                ('max_score', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('due_at', models.DateTimeField(verbose_name='muddat')),
                ('allow_late', models.BooleanField(default=True, verbose_name='kechikib topshirishga ruxsat')),
                ('attachment', models.FileField(blank=True, storage=core.storage.PrivateMediaStorage(), upload_to=core.storage.UUIDUploadPath('assignments'))),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('closed', 'Yopilgan')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='groups.group')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='schedules.lesson')),
            ],
            options={
                'verbose_name': 'vazifa',
                'verbose_name_plural': 'vazifalar',
                'ordering': ['-due_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Topshirilgan'), ('under_review', 'Tekshirilmoqda'), ('needs_revision', 'Qayta ishlash kerak'), ('graded', 'Baholangan')], db_index=True, default='submitted', max_length=20)),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('last_submitted_at', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, verbose_name='ustoz izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assignments.assignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'topshiriq',
                'verbose_name_plural': 'topshiriqlar',
                'ordering': ['-last_submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('file', models.FileField(blank=True, storage=core.storage.PrivateMediaStorage(), upload_to=core.storage.UUIDUploadPath('submissions'))),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assignments.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'topshiriq versiyasi',
                'verbose_name_plural': 'topshiriq versiyalari',
                'ordering': ['submission_id', '-number'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['group', 'status', 'due_at'], name='assignments_group_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='assignments_one_submission_per_student'),
        ),
        migrations.AddConstraint(
            model_name='submissionrevision',
            constraint=models.UniqueConstraint(fields=('submission', 'number'), name='assignments_revision_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='submissionrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), models.Q(('file', ''), _negated=True), models.Q(('link', ''), _negated=True), _connector='OR'), name='assignments_revision_has_content', violation_error_message="Matn, fayl yoki havoladan kamida bittasi bo'lishi kerak."),
        ),
    ]
