# Generated by Django 5.2.18 on 2026-10-07 10:44

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(db_index=True, verbose_name='davr (oyning 1-kuni)')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(verbose_name="to'lov muddati")),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('cancelled', 'Bekor qilingan')], default='open', max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='groups.group')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='groups.groupmembership')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hisob',
                'verbose_name_plural': 'hisoblar',
                'ordering': ['-period', '-id'],
                'indexes': [models.Index(fields=['student', 'status'], name='payments_invoice_student_idx'), models.Index(fields=['group', 'period'], name='payments_invoice_group_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'period'), name='payments_invoice_one_per_membership_period', violation_error_message='Bu oy uchun hisob allaqachon yaratilgan.'), models.CheckConstraint(condition=models.Q(('base_amount__gte', 0), ('discount_amount__gte', 0), ('amount__gte', 0)), name='payments_invoice_amounts_non_negative'), models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('base_amount'), '-', models.F('discount_amount')))), name='payments_invoice_amount_consistent')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi"), ('click', "Click (qo'lda qayd)"), ('payme', "Payme (qo'lda qayd)"), ('other', 'Boshqa')], max_length=10)),
                ('status', models.CharField(choices=[('completed', 'Qabul qilingan'), ('voided', 'Bekor qilingan')], db_index=True, default='completed', max_length=10)),
                ('paid_at', models.DateTimeField(db_index=True, verbose_name="to'langan vaqt")),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='groups.groupmembership')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "to'lov",
                'verbose_name_plural': "to'lovlar",
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['student', 'status'], name='payments_payment_student_idx'), models.Index(fields=['membership', 'status'], name='payments_payment_member_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_payment_amount_positive'), models.CheckConstraint(condition=models.Q(('status', 'completed'), ('voided_at__isnull', False), _connector='OR'), name='payments_payment_void_has_timestamp')],
            },
        ),
    ]
