# Generated by Django 5.2.18 on 2026-10-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('audience_roles', models.JSONField(blank=True, default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan")], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='organizations.branch')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='groups.group')),
            ],
            options={
                'verbose_name': "e'lon",
                'verbose_name_plural': "e'lonlar",
                'ordering': ['-is_pinned', '-published_at', '-id'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='announce_status_pub_idx')],
            },
        ),
    ]
